In [1]:
import os
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

In [2]:
environmentName = 'CartPole-v0'
env = gym.make(environmentName)

In [3]:
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        action = env.action_space.sample()
        nState, reward, done, info = env.step(action)
        score += reward
    print("Episode:{} Score:{}".format(episode, score))
env.close()

Episode:1 Score:14.0
Episode:2 Score:38.0
Episode:3 Score:13.0
Episode:4 Score:16.0
Episode:5 Score:29.0


In [4]:
env.reset()

array([ 0.00380361, -0.04757858, -0.04915532,  0.04665943])

In [5]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [6]:
env.observation_space.sample()

array([ 3.8262119e+00,  7.6927336e+37,  4.0770945e-01, -1.3396774e+38],
      dtype=float32)

In [7]:
env.step(1)

(array([ 0.00285203,  0.1482125 , -0.04822213, -0.2611183 ]), 1.0, False, {})

In [8]:
env.action_space

Discrete(2)

In [9]:
env.action_space.sample()

0

In [10]:
#Logs of Models(tensorboard)

logPath = os.path.join('Training', 'Logs')

In [11]:
logPath

'Training/Logs'

In [12]:
env = gym.make(environmentName)
env = DummyVecEnv([lambda: env])
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=logPath)

Using cpu device


In [13]:
PPO??

Init signature:
PPO(
    policy: Union[str, Type[stable_baselines3.common.policies.ActorCriticPolicy]],
    env: Union[gym.core.Env, stable_baselines3.common.vec_env.base_vec_env.VecEnv, str],
    learning_rate: Union[float, Callable[[float], float]] = 0.0003,
    n_steps: int = 2048,
    batch_size: int = 64,
    n_epochs: int = 10,
    gamma: float = 0.99,
    gae_lambda: float = 0.95,
    clip_range: Union[float, Callable[[float], float]] = 0.2,
    clip_range_vf: Union[NoneType, float, Callable[[float], float]] = None,
    ent_coef: float = 0.0,
    vf_coef: float = 0.5,
    max_grad_norm: float = 0.5,
    use_sde: bool = False,
    sde_sample_freq: int = -1,
    target_kl: Union[float, NoneType] = None,
    tensorboard_log: Union[str, NoneType] = None,
    create_eval_env: bool = False,
    policy_kwargs: Union[Dict[str, Any], NoneType] = None,
    verbose: int = 0,
    seed: Union[int, NoneType] = None,
    device: Union[torch.device, str] = 'auto',
    _init_setup_model: bool = 

In [14]:
model.learn(total_timesteps=20000)

Logging to Training/Logs/PPO_5
-----------------------------
| time/              |      |
|    fps             | 1071 |
|    iterations      | 1    |
|    time_elapsed    | 1    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 709         |
|    iterations           | 2           |
|    time_elapsed         | 5           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.009325857 |
|    clip_fraction        | 0.103       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | -3.6e-05    |
|    learning_rate        | 0.0003      |
|    loss                 | 7.67        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.015      |
|    value_loss           | 54.1        |
-----------------------------------------
---

In [15]:
ppoPath = os.path.join('Training', 'SavedModels', 'PPOCartpoleModel' )
ppoPath

'Training/SavedModels/PPOCartpoleModel'

In [16]:
model.save(ppoPath)

In [17]:
# Load model

#del model
#model.learn(total_timesteps=1000)
#model.load(ppoPath, env=env)

In [18]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

/opt/anaconda3/lib/python3.8/site-packages/stable_baselines3/common/evaluation.py:65: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


(200.0, 0.0)

In [53]:
episodes = 5
for episode in range(1, episodes+1):
    obs = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        #using the Model here
        action, _ = model.predict(obs)
        obs, reward, done, info = env.step(action)
        score += reward
    print("Episode:{} Score:{}".format(episode, score))


Episode:1 Score:[158.]
Episode:2 Score:[200.]
Episode:3 Score:[200.]
Episode:4 Score:[194.]
Episode:5 Score:[200.]


In [24]:
print("[CartPosition, CartVelocity, PoleAngle, PoleAngularVelocity]")
obs

[CartPosition, CartVelocity, PoleAngle, PoleAngularVelocity]


array([[-0.03322764, -0.03074235,  0.0384668 ,  0.02758993]],
      dtype=float32)

In [27]:
print("Reward = '1' for every step taken including the Termination step")
action, _ = model.predict(obs)
env.step(action)

Reward = '1' for every step taken including the Termination step


(array([[-0.03120332, -0.22744139,  0.03500471,  0.35522038]],
       dtype=float32),
 array([1.], dtype=float32),
 array([False]),
 [{}])

In [29]:
#Tensorboard
trainingLogPath = os.path.join(logPath, 'PPO_2')
trainingLogPath

'Training/Logs/PPO_2'

In [ ]:
#!tensorboard --logdir={trainingLogPath}

In [33]:
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold

In [39]:
stopCallback = StopTrainingOnRewardThreshold(reward_threshold=200, verbose=1)
evalCallback = EvalCallback(env,
                            callback_on_new_best=stopCallback,
                            eval_freq=10000,
                            best_model_save_path=os.path.join('Training', 'SavedModels'),
                            verbose=1)

In [40]:
modelU = PPO('MlpPolicy', env, verbose=1, tensorboard_log=logPath)

Using cpu device


In [41]:
modelU.learn(total_timesteps=20000, callback=evalCallback)

Logging to Training/Logs/PPO_6
-----------------------------
| time/              |      |
|    fps             | 1142 |
|    iterations      | 1    |
|    time_elapsed    | 1    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 785         |
|    iterations           | 2           |
|    time_elapsed         | 5           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008960754 |
|    clip_fraction        | 0.115       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | -0.000198   |
|    learning_rate        | 0.0003      |
|    loss                 | 5.67        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0193     |
|    value_loss           | 52.1        |
-----------------------------------------
---

In [42]:
# New Neural Network
newNN = [dict(pi=[128,128,128,128], vf=[128,128,128,128])]

In [43]:
modelNewNN = PPO('MlpPolicy', env, 
                 verbose=1, 
                 tensorboard_log=logPath, 
                 policy_kwargs={'net_arch':newNN})
modelNewNN.learn(total_timesteps=20000, callback=evalCallback)

Using cpu device
Logging to Training/Logs/PPO_7
-----------------------------
| time/              |      |
|    fps             | 878  |
|    iterations      | 1    |
|    time_elapsed    | 2    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 477         |
|    iterations           | 2           |
|    time_elapsed         | 8           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.013867734 |
|    clip_fraction        | 0.217       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.681      |
|    explained_variance   | -0.00255    |
|    learning_rate        | 0.0003      |
|    loss                 | 2.59        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0265     |
|    value_loss           | 19.5        |
----------------------------

# Using an Alternative Algorithm (DQN):

In [46]:
from stable_baselines3 import DQN

modelDQN = DQN('MlpPolicy', 
                env, 
                verbose=1, 
                tensorboard_log=logPath)

modelDQN.learn(total_timesteps=20000)

Using cpu device
Logging to Training/Logs/DQN_1
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.956    |
| time/               |          |
|    episodes         | 4        |
|    fps              | 3229     |
|    time_elapsed     | 0        |
|    total_timesteps  | 93       |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.894    |
| time/               |          |
|    episodes         | 8        |
|    fps              | 3360     |
|    time_elapsed     | 0        |
|    total_timesteps  | 223      |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.853    |
| time/               |          |
|    episodes         | 12       |
|    fps              | 3210     |
|    time_elapsed     | 0        |
|    total_timesteps  | 309      |
----------------------------------
-------

In [47]:
dqnPath = os.path.join('Training', 'SavedModels', 'DQNModel')

modelDQN.save(dqnPath)

In [48]:
evaluate_policy(modelDQN, env, n_eval_episodes=10, render=True)

(9.1, 0.7000000000000001)

In [56]:
episodes = 20
for episode in range(1, episodes+1):
    obs = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        #using the Model here
        action, _ = modelDQN.predict(obs)
        obs, reward, done, info = env.step(action)
        score += reward
    print("Episode:{} Score:{}".format(episode, score))
env.close()

Episode:1 Score:[10.]
Episode:2 Score:[8.]
Episode:3 Score:[10.]
Episode:4 Score:[10.]
Episode:5 Score:[9.]
Episode:6 Score:[13.]
Episode:7 Score:[10.]
Episode:8 Score:[8.]
Episode:9 Score:[10.]
Episode:10 Score:[9.]
Episode:11 Score:[9.]
Episode:12 Score:[8.]
Episode:13 Score:[9.]
Episode:14 Score:[11.]
Episode:15 Score:[9.]
Episode:16 Score:[9.]
Episode:17 Score:[9.]
Episode:18 Score:[10.]
Episode:19 Score:[10.]
Episode:20 Score:[10.]
